name: Main

on:
  pull_request:
  push:
    branches: 
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
  
  typecheck:
    name: Type Check
    needs: lint
    uses: ./.github/workflows/typecheck.yaml
  
  tests:
    name: Tests
    needs: [lint, typecheck]
    uses: ./.github/workflows/tests.yaml

  snyk:
    name: Snyk
    needs: [lint, typecheck, tests]
    uses: ./.github/workflows/snyk.yaml
    secrets: inherit